### ISSUE TITLE
Data display for selected person

### ISSUE THREAD

**Issue by kkott** [patrickkidd/family-diagram#8]
v.1.0.0b3
MacOS El Capitan v.10.11.6
MacBook Pro, late 2011

When a person is selected (highlighted) the data associated with the person does not display. What was your thinking in designing the display this way? I can live with it but would prefer seeing the data.

**Comment by patrickkidd** [comment]
The problem is that you don't want to see the properties if you want to drag or delete the person, or select and move or delete many people/marriages/emotional process symbols. So the workflow is single-click to select, and double-click or single-click with the "i" button on the top toolbar to show the properties. Let me know if there is still a hole in my thinking.

**Comment by kkott** [comment]
Makes sense.

**Comment by patrickkidd** [comment]
For what it’s worth, you can also click once and have your left hand ready to do the cmd-i shortcut to “inspect” the newly selected person.
